### ISSUE TITLE
User groups - scroll UI

### ISSUE THREAD

**Issue by nechalmaggon** [ToolJet/ToolJet#9957]
**Where?**
- User groups container

**What to fix?** 
- Dark mode 
- Scroll to be visible and shown only on hover of the container and not constantly (for Chrome and Safari browsers)

<img width="1440" alt="Screenshot 2024-06-03 at 3 25 08 PM" src="https://github.com/ToolJet/ToolJet/assets/127945292/ea86facb-3205-4495-8506-24345d89ade8">

Uploading Screen Recording 2024-06-03 at 3.32.19 PM.mov…

**Comment by CuriousCoder00** [comment]
@PriteshKiri This issue's been fixed in later versions...
![image](https://github.com/user-attachments/assets/ff970511-bc28-405f-8c78-c3190df6b7f5)

**Comment by PriteshKiri** [comment]
@CuriousCoder00 let me check and get back to you.

**Comment by ShyanRoyChoudhury** [comment]
@PriteshKiri All the scroll issues in UI are similar to the ones I posted a PR for https://github.com/ToolJet/ToolJet/pull/10180

**Comment by PriteshKiri** [comment]
@ShyanRoyChoudhury issues are different on different browsers. We will soon update the issue description.

**Comment by PriteshKiri** [comment]
The issue is updated. And is up for grabs for the community :)

**Comment by CuriousCoder00** [comment]
This issue is again for Version `2.38.0-e2.17.0`
Can you please update this issue as the current issue has been resolved on newer version..

**Comment by PriteshKiri** [comment]
Hey @CuriousCoder00, as we have mentioned in the description, the issue is still there for Chrome and Safari browsers.

**Comment by Abhishek-90** [comment]
I would like to take it up.

**Comment by SRIKARREDDY-dotorg** [comment]
I have verified that this issue is not repro-able in the chrome Version 127.0.6533.100, with the tooljet Version 2.63.0

Chrome
https://github.com/user-attachments/assets/34f4d9d6-9582-4ddb-9ec7-f1b376d95158

Safari
https://github.com/user-attachments/assets/5cb98153-d0d8-40b2-b326-76e048f888fa

**Comment by PriteshKiri** [comment]
Hey @SRIKARREDDY-dotorg,

Thanks for sharing the videos. But to clarify, the issue is the scroll not being visible. As in the videos, scrolls are also not visible. We want the scroll to be visible when hovering over the containers.

**Comment by PriteshKiri** [comment]
@Abhishek-90 are you still interested in working on this issue?

**Comment by Abhishek-90** [comment]
Yes @PriteshKiri , you can assign it to me.

**Comment by PriteshKiri** [comment]
Hey @Abhishek-90, any update on the issue?

In case if you are facing any issues, please feel free to drop your queries in the contributor's channel of our [Slack community](https://tooljet.com/slack)

**Comment by CuriousCoder00** [comment]
@PriteshKiri Can you assing this issue to me? I'd love to take it up?

**Comment by Abhishek-90** [comment]
> Hey @Abhishek-90, any update on the issue?
> 
> 
> 
> In case if you are facing any issues, please feel free to drop your queries in the contributor's channel of our [Slack community](https://tooljet.com/slack)

No issues till now @PriteshKiri , will get it resolved in a day or two.

**Comment by CuriousCoder00** [comment]
If it's yet to be resolved, you can assign it to me. I would love working on it.

**Comment by Abhishek-90** [comment]
@PriteshKiri you can assign it to @CuriousCoder00 as my local setup issue is not yet resolved and there is not point in blocking the issue. Will take up another issue once my local setup is working properly, thankyou!

**Comment by PriteshKiri** [comment]
@Abhishek-90 we will soon try to fix your local setup issue. Unassigning it for now. Feel free to drop a comment once your setup is up.

**Comment by PriteshKiri** [comment]
@CuriousCoder00 , We greatly appreciate your interest. However, we would like to wait and see if there are any first-time contributors who are also interested in this opportunity. 

We hope you understand our decision and thank you for your understanding.

**Comment by Abhishek-90** [comment]
> @Abhishek-90 we will soon try to fix your local setup issue. Unassigning it for now. Feel free to drop a comment once your setup is up.

Thankyou @PriteshKiri , My local setup is up and running as of now. You can reassign it to me. Thankyou!

**Comment by PriteshKiri** [comment]
Assigned @Abhishek-90. Happy coding :)

**Comment by PriteshKiri** [comment]
Hey @Abhishek-90, any updates on the issue?

**Comment by PriteshKiri** [comment]
@Abhishek-90 are you still working on the issue? Please let me know if you are facing any issues.

**Comment by PriteshKiri** [comment]
Unassigning due to lack of progress.

**Comment by SRIKARREDDY-dotorg** [comment]
Can you please assign it to me? I haven't worked on a single bug before

**Comment by PriteshKiri** [comment]
assigned @SRIKARREDDY-dotorg! Happy coding :)

If you have any questions, please feel free to drop them in the contributors' channel of our [Slack community](https://tooljet.com/slack).

**Comment by SRIKARREDDY-dotorg** [comment]
I have fixed for the Users tab above the groups. Is it ok if I raise the PR for that first and review it?

Please let me if this user-experience works.

https://github.com/user-attachments/assets/8e2df2f5-003b-44e1-a2eb-d35782d31c10

**Comment by SRIKARREDDY-dotorg** [comment]
I have created PR https://github.com/ToolJet/ToolJet/pull/10754 based on the places where I can see the scrollable will be beneficial such as scroll users, user-groups, data-sources.

**Comment by PriteshKiri** [comment]
Hey @SRIKARREDDY-dotorg, thanks for the quick PR. The video looks good. I hope you have tested this for both Chrome and Safari.

Will into the message issue. Thanks for pointing out.

`Quick PR`

**Comment by SRIKARREDDY-dotorg** [comment]
Yes did for both the browsers. I will upload the other one by EOD
